### PR TITLE
Fix UI import statement

### PR DESCRIPTION
**Pull request by joshfrench**
My bad! I botched the import on `Mobiledoc.UI`. I had a bit of a challenge trying to verify this in your dev env while being unfamiliar with Broccoli and Ember, do you mind checking it before you ship this patch? Thanks!

### CODE REVIEW

**Comment by bantic** [comment]
@joshfrench No worries. This looks right to me. I will test it out more fully later but can release a beta now.

**Comment by bantic** [comment]
@joshfrench This is released on v0.10.11-beta.1 if you want to make sure it works now for you.

**Comment by joshfrench** [comment]
The beta works for me, thanks and sorry for that. I just pushed another commit to this branch that exposes `UI`, `Range`, and `Position` as named imports in addition to `Editor`, if you feel like grabbing that as well. (Otherwise they remain available at `Mobiledoc.default.*`)

**Comment by bantic** [comment]
Cool, yeah, I'm pulling that in on #493. thanks!

**Comment by bantic** [comment]
released in [v0.10.11](https://github.com/bustlelabs/mobiledoc-kit/releases/tag/v0.10.11)

**Comment by joshfrench** [comment]
Thanks Cory!

**Pull request merged**
