### PR TITLE
Fix bug #326: Cross-browser testing on CI

### PR DESCRIPTION
**Pull request by YoranBrondsema**
Integrate Sauce Labs into CI to test on different browsers. 

### Chrome ###
Latest version, currently 48.

### Firefox ###
Latest version, currently 44.

### IE11 ###
Had to disable some tests in order to pass the suite (added TODOs). I further had problems with all copy-pasting tests as the browser requires to manually allow setting data in the clipboard. A way has to be found to do this automatically (see https://answers.microsoft.com/en-us/ie/forum/ie11-iewindows8_1/clipboard-access-in-ie-11/94ab3483-828a-4e55-974a-cb4cc98e94c7).

### Edge ###
Latest version.

### Safari 9 (enabled) ###
All good.

## Comments ##

* @bantic You had only given me the Sauce Labs access code but the username of the account is also required. In order to ease setting up, I created an account myself. Obviously, this will have to be replaced with you account.
* Also, I don't know what the best way is to store the `SAUCE_USERNAME` and `SAUCE_ACCESS_KEY` environment variables.

## Other changes ##
* Update `testem` to 1.4.0

### CODE REVIEW

**Comment by bantic** [comment]
@YoranBrondsema Thank you! Can we travis-encrypt the sauce account/username for CI? I'll review this locally soon, hopefully tonight.

**Comment by bantic** [comment]
> Can we travis-encrypt the sauce account/username for CI

If that's viable, I will encrypt and add the official mobiledoc-kit sauce labs credentials into the .travis.yml

**Comment by YoranBrondsema** [comment]
> If that's viable, I will encrypt and add the official mobiledoc-kit sauce labs credentials into the .travis.yml

That should be possible in theory, although I don't know if it's directly supported by `saucie` (https://github.com/johanneswuerbach/saucie). However, in any case it should be done I think!

**Comment by bantic** [comment]
@YoranBrondsema this looks great. Is it possible to configure the sauce connection through travis/testem such that it shows the phantom results inline but groups the per-browser results as a single result, the way they do in [glimmer's CI](https://travis-ci.org/tildeio/glimmer/builds/108684786)? Scroll down to the end where you'll see lines like: 
```
ok 390 SL_Chrome_Current - https://saucelabs.com/jobs/97125e2afb4748468a050485c2f0c4ef
ok 391 SL_Chrome_Last - https://saucelabs.com/jobs/70393bd1aee44116b0631b1c6b841330
ok 392 SL_Firefox_Current - https://saucelabs.com/jobs/d2e4de2ecbc24d60a3727e33aa28d97a`
```

**Comment by YoranBrondsema** [comment]
> Is it possible to configure the sauce connection through travis/testem such that it shows the phantom results inline but groups the per-browser results as a single result, the way they do in glimmer's CI?

Sure thing, done.

Some other things:
* I managed to get Safari 9 running
* I think you can relatively easily encrypt the SL access key on Travis (see https://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables). I'm not sure it's possible to do this from a fork so you might have to do this.
* Once it's all set up and on master, a badge can be added to the README (https://wiki.saucelabs.com/display/DOCS/Using+Status+Badges+and+the+Browser+Matrix+Widget+to+Monitor+Test+Results)


SL Badge (https://wiki.saucelabs.com/display/DOCS/Using+Status+Badges+and+the+Browser+Matrix+Widget+to+Monitor+Test+Results)
Encrypt with travis (https://docs.travis-ci.com/user/environment-variables/)

**Comment by bantic** [comment]
@YoranBrondsema This is great. Just two more things:
Can we restore the phantomjs output (in full — individual lines per test) and then would you mind squashing the commits? This looks great, I am very pleased to have these tests going.

**Comment by YoranBrondsema** [comment]
@bantic Cool no worries. I restored PhantomJS, added Edge and squashed the commits. Let me know if there's something I forgot!

**Comment by bantic** [comment]
awesome! Thank you

**Pull request merged**
